import Foundation

// MARK: - Mock Data Helper для создания скриншотов
class MockDataHelper {
    
    static func createMockEvents() -> [SportEvent] {
        let dateFormatter = ISO8601DateFormatter()
        dateFormatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        
        // Создаем моковые города
        let moscow = City(id: 1, name: "Москва")
        let spb = City(id: 2, name: "Санкт-Петербург")
        let sochi = City(id: 3, name: "Сочи")
        
        // Создаем моковые виды спорта
        let running = Sport(id: 1, name: "Бег", iconName: "running_icon")
        let cycling = Sport(id: 2, name: "Велоспорт", iconName: "cycling_icon")
        let swimming = Sport(id: 3, name: "Плавание", iconName: "swimming_icon")
        let tennis = Sport(id: 4, name: "Теннис", iconName: "tennis_icon")
        let golf = Sport(id: 5, name: "Гольф", iconName: "golf_icon")
        
        let events = [
            SportEvent(
                id: 1,
                name: "Московский марафон 2024",
                date: dateFormatter.date(from: "2024-09-15T09:00:00.000Z") ?? Date(),
                photoMain: nil,
                photoFeed: nil,
                iconNames: "running_icon",
                fullDescription: "Крупнейшее беговое событие России. Дистанции: марафон (42,2 км), полумарафон (21,1 км), забег на 10 км и детский забег 1 км. Старт и финиш на Красной площади.",
                shortDescription: "Главное беговое событие года в столице",
                organizer: "Moscow Marathon",
                websiteUrl: "https://moscowmarathon.org",
                availableDistances: "42.2 км, 21.1 км, 10 км, 1 км",
                eventFormat: "Массовый старт",
                ageCategories: "16+",
                address: "Красная площадь, Москва",
                latitude: 55.7539,
                longitude: 37.6208,
                contactPhone: "+7 495 123-45-67",
                contactEmail: "info@moscowmarathon.org",
                registrationUrl: "https://moscowmarathon.org/register",
                registrationDeadline: dateFormatter.date(from: "2024-09-01T23:59:59.000Z"),
                maxParticipants: 30000,
                currentParticipants: 24500,
                price: "3500-8500 ₽",
                photoGallery: nil,
                videoUrl: nil,
                cityId: 1,
                city: moscow,
                sports: [running],
                files: [],
                cityName: "Москва",
                sportName: "Бег",
                isUpcoming: true,
                canRegister: true,
                occupancyPercentage: 0.82,
                availableSpots: 5500,
                availableDistancesArray: ["42.2 км", "21.1 км", "10 км", "1 км"]
            ),
            
            SportEvent(
                id: 2,
                name: "Велогонка Сочи Олимпик",
                date: dateFormatter.date(from: "2024-10-20T08:30:00.000Z") ?? Date(),
                photoMain: nil,
                photoFeed: nil,
                iconNames: "cycling_icon",
                fullDescription: "Международная велогонка по олимпийским трассам. Горные и шоссейные дистанции для всех уровней подготовки.",
                shortDescription: "Велогонка по олимпийским трассам",
                organizer: "Sochi Olympic Cycling",
                websiteUrl: "https://sochicycling.ru",
                availableDistances: "120 км, 60 км, 30 км",
                eventFormat: "Групповая гонка",
                ageCategories: "18+",
                address: "Олимпийский парк, Сочи",
                latitude: 43.4060,
                longitude: 39.9560,
                contactPhone: "+7 862 234-56-78",
                contactEmail: "info@sochicycling.ru",
                registrationUrl: "https://sochicycling.ru/register",
                registrationDeadline: dateFormatter.date(from: "2024-10-05T23:59:59.000Z"),
                maxParticipants: 1500,
                currentParticipants: 1200,
                price: "2000-5000 ₽",
                photoGallery: nil,
                videoUrl: nil,
                cityId: 3,
                city: sochi,
                sports: [cycling],
                files: [],
                cityName: "Сочи",
                sportName: "Велоспорт",
                isUpcoming: true,
                canRegister: true,
                occupancyPercentage: 0.80,
                availableSpots: 300,
                availableDistancesArray: ["120 км", "60 км", "30 км"]
            ),
            
            SportEvent(
                id: 3,
                name: "Заплыв через Неву",
                date: dateFormatter.date(from: "2024-08-25T07:00:00.000Z") ?? Date(),
                photoMain: nil,
                photoFeed: nil,
                iconNames: "swimming_icon",
                fullDescription: "Традиционный заплыв через Неву. Дистанции от 1 км до 5 км. Участие только для опытных пловцов.",
                shortDescription: "Традиционный заплыв в центре города",
                organizer: "St. Petersburg Swimming Club",
                websiteUrl: "https://nevaswimming.spb.ru",
                availableDistances: "5 км, 3 км, 1 км",
                eventFormat: "Массовый заплыв",
                ageCategories: "20+",
                address: "Дворцовая набережная, СПб",
                latitude: 59.9398,
                longitude: 30.3146,
                contactPhone: "+7 812 345-67-89",
                contactEmail: "info@nevaswimming.spb.ru",
                registrationUrl: "https://nevaswimming.spb.ru/register",
                registrationDeadline: dateFormatter.date(from: "2024-08-15T23:59:59.000Z"),
                maxParticipants: 500,
                currentParticipants: 450,
                price: "1500-3000 ₽",
                photoGallery: nil,
                videoUrl: nil,
                cityId: 2,
                city: spb,
                sports: [swimming],
                files: [],
                cityName: "Санкт-Петербург",
                sportName: "Плавание",
                isUpcoming: false,
                canRegister: false,
                occupancyPercentage: 0.90,
                availableSpots: 50,
                availableDistancesArray: ["5 км", "3 км", "1 км"]
            ),
            
            SportEvent(
                id: 4,
                name: "Открытый турнир по теннису",
                date: dateFormatter.date(from: "2024-11-10T10:00:00.000Z") ?? Date(),
                photoMain: nil,
                photoFeed: nil,
                iconNames: "tennis_icon",
                fullDescription: "Любительский турнир по теннису. Категории: мужчины, женщины, парный разряд. Призы и подарки всем участникам.",
                shortDescription: "Любительский турнир для всех уровней",
                organizer: "Moscow Tennis Association",
                websiteUrl: "https://tennis-moscow.ru",
                availableDistances: "Одиночный и парный разряд",
                eventFormat: "Турнир на выбывание",
                ageCategories: "16+",
                address: "Теннисный клуб 'Чемпион', Москва",
                latitude: 55.7558,
                longitude: 37.6173,
                contactPhone: "+7 495 456-78-90",
                contactEmail: "tournament@tennis-moscow.ru",
                registrationUrl: "https://tennis-moscow.ru/tournament",
                registrationDeadline: dateFormatter.date(from: "2024-11-01T23:59:59.000Z"),
                maxParticipants: 64,
                currentParticipants: 35,
                price: "2500 ₽",
                photoGallery: nil,
                videoUrl: nil,
                cityId: 1,
                city: moscow,
                sports: [tennis],
                files: [],
                cityName: "Москва",
                sportName: "Теннис",
                isUpcoming: true,
                canRegister: true,
                occupancyPercentage: 0.55,
                availableSpots: 29,
                availableDistancesArray: ["Одиночный разряд", "Парный разряд"]
            ),
            
            SportEvent(
                id: 5,
                name: "Гольф-турнир 'Осенний кубок'",
                date: dateFormatter.date(from: "2024-09-28T08:00:00.000Z") ?? Date(),
                photoMain: nil,
                photoFeed: nil,
                iconNames: "golf_icon",
                fullDescription: "Престижный турнир по гольфу на 18 лунок. Участие по приглашениям и регистрации. Профессиональный гольф-клуб.",
                shortDescription: "Элитный турнир по гольфу",
                organizer: "Premium Golf Club",
                websiteUrl: "https://premiumgolf.ru",
                availableDistances: "18 лунок",
                eventFormat: "Индивидуальная игра",
                ageCategories: "21+",
                address: "Гольф-клуб 'Премиум', Подмосковье",
                latitude: 55.6419,
                longitude: 37.5172,
                contactPhone: "+7 495 789-01-23",
                contactEmail: "tournament@premiumgolf.ru",
                registrationUrl: "https://premiumgolf.ru/autumn-cup",
                registrationDeadline: dateFormatter.date(from: "2024-09-20T23:59:59.000Z"),
                maxParticipants: 120,
                currentParticipants: 85,
                price: "15000 ₽",
                photoGallery: nil,
                videoUrl: nil,
                cityId: 1,
                city: moscow,
                sports: [golf],
                files: [],
                cityName: "Москва",
                sportName: "Гольф",
                isUpcoming: true,
                canRegister: true,
                occupancyPercentage: 0.71,
                availableSpots: 35,
                availableDistancesArray: ["18 лунок"]
            )
        ]
        
        return events
    }
}